# Project glue

<!-- Generated by the chisel setup questionnaire (sections A–H below). This
file is the GLUE: the single indirection point the discipline, the pipeline
steps and the skills read to resolve project-specific paths and behaviour.
`init` writes it once from the questionnaire answers below (each pre-filled
with its default); `update` re-renders the managed parts of the socle but never
touches this file.

Its personal counterpart is `.agents/user.md` — one per dev, never committed,
posed from `.agents/user.md.tpl`. A fact everyone's agents need belongs HERE;
a fact true of one machine or one account belongs there. -->

## A · Task workspace

<!-- Questionnaire asks: where do tasks, archive, changelog, roadmap, and the
task template live? Default is root `/project-management/`; an
Astro-embedded variant may nest it elsewhere.

The changelog line is the ONE place the journal's path is declared: everything
that writes to it — the pipeline steps, the skills — resolves through this line
and never hardcodes a name. Its default is `LOG.md` because a repo's
`CHANGELOG.md` usually belongs to its releases, and this is a different
document. A repo equipped before that default changed simply keeps its own name
here; nothing else has to move.

That journal is WRITTEN BY HAND — one dated entry per task, added by the agent
at the end of the work. It is never generated: not from a coordination
database's audit trail, not from the git history, not from anything else. It is
narration, and narration nobody wrote is worth nothing to the next reader.
Architecture decision records are a separate artifact and none of this touches
them. -->

- **Tasks root:** `/project-management/`
- **Tasks:** `/project-management/tasks/`
- **Archive:** `/project-management/archive/`
- **Changelog:** `/project-management/LOG.md`
- **Roadmap:** `/project-management/ROADMAP.md`
- **Task file template:** `/project-management/000-task-file-template.md`
- **Task id script:** `/scripts/task-id.sh`

## B · Coordination

<!-- Two decisions, asked separately by the questionnaire and readable
separately here: B1 where task statuses live, B2 whether tasks point back to
tickets in another tool. Everything that needs coordination state — the
pipeline steps, the skills — resolves through this section and never hardcodes
a tool. -->

### B1 · Where task statuses live

**Statuses: in the task files.** Work is tracked as task files in this repo;
each one carries its own status.

- **Active tasks:** `<Tasks>/<time-id>-<intention>.md` (see Section A),
  where `<time-id>` is generated by `<Task id script>` (`YYYYMMDD-HHmm`, for
  automatic chronological sorting). Large tasks may be split into slice files
  under `<Tasks>/<time-id>-<feature-slug>/<NN>-<slice-slug>.md`, numbered in
  dependency order (see the `slice-task` skill)
- **Completed tasks:** moved to `<Archive>` (see Section A)
- **Format:** the template at `<Task file template>` (see Section A)
  (reading-gradient zones: 🧑 review carefully / 🧑 review if relevant / 🤖
  agent zone)
- **Status:** the `**Status:**` field in each task file (🔴 🟡 🟠 🟢 ⚪ ⚫)
- **Work the frontier:** any task/slice whose blockers are all done can start

<!-- The two other cases, and what this block says instead when one of them is
chosen (the questionnaire rewrites it; task FILES keep the content in every
case — only the statuses and the blocking edges move):

- **a database committed next to the files** — statuses, blocking edges and
  "what is ready to start" are answered by one command instead of a reading
  session. Requires the `bd` tool, 1.2.2 or newer, and follows the convention
  at `.agents/skills/chisel-beads/SKILL.md`. The habit it costs: pull at
  the start of a session, push at the end. Never `git push --mirror` (it
  destroys the tool's own refs)
- **the same database, served by a local background process** — for ONE
  machine running several agents at the same time, which would otherwise trip
  over each other. It is NOT the answer to "we are several people": several
  people on several machines are served by the committed database above

Either of them replaces the State line below with `- [ ] initialised`, ticked
only once the database has actually been created — the choice recorded here
and the state on disk are two different facts, and nothing may assume the
second from the first. Creating it (and the working convention that comes with
it) is a separate, named step of the setup, not something an agent improvises.

Moving from files to a database later is tooled and only touches tasks that
are still open. Moving back is a `git revert` on the spot; later than that, by
hand. -->

- **State:** the task files ARE the state — nothing to initialise.
- **Other cases:** a database committed next to the files, or that same
  database served by a local process for several agents running at once on ONE
  machine. Re-run the setup's first coordination question to change case; the
  move from files to a database is tooled and only touches open tasks.

### B2 · Link to an external tracker

**External tracker: none.** Tasks live in this repo and point at nothing
outside it.

- **Adapter page:** _(none — no external tracker)_

When a tracker IS wired up, this section is the only place that says so, and it
says three things: **which tracker**, **where the link back lives**, and **the
adapter page** that describes the tracker. Nothing is ever synchronised in both
directions — the task file stays the place where the work is described; when
the external ticket owns the business spec, check it for updates before working
on a task derived from it.

**The list of trackers is open.** Adding one later = writing one adapter page
and naming it on the line above. No change to the toolkit, no change to any
skill, no new mechanism.

<!-- The three things, in full, for whoever wires one up:

1. **which tracker**, by name, in the verdict line at the top;
2. **where the link back lives** — the `external_ref` field of the
   coordination record when B1 keeps statuses in a database, or a
   `**Ticket:** <url>` line under the task's Status when it does not. ONE
   place, so a reader always knows where to look;
3. **the adapter page** — one page saying how to read a ticket there, what to
   copy into the task file, and what (if anything) goes back. It lives with the
   living docs declared in Section D, and its path goes on the Adapter page
   line above. -->

## C · Reading list

<!-- Questionnaire asks: what should a fresh agent session read at start, to
load context cheaply? Boilerplate projects get this prefilled; brownfield
repos get scanned and the list built with assistance. -->

- `README.md`
- `<Changelog>` (see Section A) — most recent entries

## D · Documentation reference

<!-- Questionnaire asks: where do the living, evergreen docs (as-built
architecture, domain pages) live, outside the task workspace? -->

- **Living docs root:** `doc/**` (outside the task workspace declared in
  Section A)
- Boilerplate variant: `apps/documentation` (THE doc reference — business +
  architecture, no split)

## E · Adapters

<!-- Written by `init`, listed here for `check` to verify — not asked by the
questionnaire directly. -->

- [ ] `AGENTS.md` (source of truth, managed block)
- [ ] `CLAUDE.md` (`@AGENTS.md` import)
- [ ] `.claude/skills` → `.agents/skills` (symlink)
- [ ] `.claude/agents` (role definitions rendered from `.agents/profiles/`)
- [ ] `.codex/agents` (role definitions rendered from `.agents/profiles/`)

## F · Gate commands

<!-- Questionnaire asks: lint / test / build / browser-check commands,
prefilled from repo exploration + package.json where possible. -->

- **Lint:** _(none configured — example: `npm run lint`)_
- **Test:** _(none configured — example: `npm test`)_
- **Build:** _(none configured — example: `npm run build`)_
- **Browser check:** _(none configured — example: `npm run dev` + manual check)_

## G · Glossary & decisions

<!-- Questionnaire asks: where does the domain glossary live, and where are
ADRs recorded? Decisions LINK existing rationale — never duplicate it. -->

- **Glossary:** root `CONTEXT.md`
- **ADRs:** `docs/adr/`
- Boilerplate variant: both inside `apps/documentation` (see Section D)

## H · Model tiers

<!-- Questionnaire asks: has the team agreed on which concrete model each tier
means for THIS repo? Most have not, and leave this unset. This is the middle
rung of the cascade — `.agents/user.md` (personal, never committed) wins over
it, and the socle default catches whatever neither answers. What the tiers ARE
and how they resolve is written once, in `.agents/methodology.md`, section
"Model tiers (and how they resolve)"; do not restate it here.

To set one, uncomment the lines below and name a model your team's tools all
expose. A tier left unset simply falls through. -->

- **Team mapping:** _(not set — each dev's `.agents/user.md`, then the socle
  default, answer)_

<!--
- **frontier:** <model id>
- **mid:** <model id>
- **cheap:** <model id>
-->
