# Project glue

<!-- Generated by the chisel setup questionnaire (sections A–G below). This
file is the GLUE: the single indirection point rules and skills read to
resolve project-specific paths and behaviour. `init` writes it once from the
questionnaire answers below (each pre-filled with its default); `update`
re-renders the managed parts of the socle but never touches this file. -->

## A · Task workspace

<!-- Questionnaire asks: where do tasks, archive, changelog, roadmap, and the
task template live? Default is root `/project-management/`; an
Astro-embedded variant may nest it elsewhere. -->

- **Tasks root:** `/project-management/`
- **Tasks:** `/project-management/tasks/`
- **Archive:** `/project-management/archive/`
- **Changelog:** `/project-management/CHANGELOG.md`
- **Roadmap:** `/project-management/ROADMAP.md`
- **Task file template:** `/project-management/000-task-file-template.md`
- **Task id script:** `/scripts/task-id.sh`

## B · Tracker

<!-- Questionnaire asks: local markdown (the default), or an external
tracker (GitHub Issues, Plane)? This section absorbs what used to be a
separate issue-tracker doc in the socle — rules and skills that referenced
it now read this section instead; nothing else changes when the tracker
changes. -->

**Mode: local markdown.** Work is tracked as task files in this repo — there
is no external tracker wired up for now.

- **Active tasks:** `<Tasks>/<time-id>-<intention>.md` (see Section A),
  where `<time-id>` is generated by `<Task id script>` (`YYYYMMDD-HHmm`, for
  automatic chronological sorting). Large tasks may be split into slice files
  under `<Tasks>/<time-id>-<feature-slug>/<NN>-<slice-slug>.md`, numbered in
  dependency order (see the `slice-task` skill)
- **Completed tasks:** moved to `<Archive>` (see Section A)
- **Format:** the template at `<Task file template>` (see Section A)
  (reading-gradient zones: 🧑 review carefully / 🧑 review if relevant / 🤖
  agent zone)
- **Status:** the `**Status:**` field in each task file (🔴 🟡 🟠 🟢 ⚪ ⚫)
- **Work the frontier:** any task/slice whose blockers are all done can start

### Switching to an external tracker later

To move to Linear, GitHub Issues, or Plane, rewrite this section with the new
workflow (how to fetch a ticket, how to publish, which labels). The skills and
rules read this file — nothing else needs to change. When an external tracker
owns the business spec, the agent must check the ticket for updates before
working on a task derived from it.

## C · Reading list

<!-- Questionnaire asks: what should a fresh agent session read at start, to
load context cheaply? Boilerplate projects get this prefilled; brownfield
repos get scanned and the list built with assistance. -->

- `README.md`
- `<Changelog>` (see Section A) — most recent entries

## D · Documentation reference

<!-- Questionnaire asks: where do the living, evergreen docs (as-built
architecture, domain pages) live, outside the task workspace? -->

- **Living docs root:** `doc/**` (outside the task workspace declared in
  Section A)
- Boilerplate variant: `apps/documentation` (THE doc reference — business +
  architecture, no split)

## E · Adapters

<!-- Written by `init`, listed here for `check` to verify — not asked by the
questionnaire directly. -->

- [ ] `AGENTS.md` (source of truth, managed block)
- [ ] `CLAUDE.md` (`@AGENTS.md` import)
- [ ] `.claude/skills` → `.agents/skills` (symlink)

## F · Gate commands

<!-- Questionnaire asks: lint / test / build / browser-check commands,
prefilled from repo exploration + package.json where possible. -->

- **Lint:** _(none configured — example: `npm run lint`)_
- **Test:** _(none configured — example: `npm test`)_
- **Build:** _(none configured — example: `npm run build`)_
- **Browser check:** _(none configured — example: `npm run dev` + manual check)_

## G · Glossary & decisions

<!-- Questionnaire asks: where does the domain glossary live, and where are
ADRs recorded? Decisions LINK existing rationale — never duplicate it. -->

- **Glossary:** root `CONTEXT.md`
- **ADRs:** `docs/adr/`
- Boilerplate variant: both inside `apps/documentation` (see Section D)
