// Per-tool agent definitions, rendered from the canonical profiles.
//
// No tool can import a shared definition, so chisel generates one per tool
// from the same source: the profile body IS the contract, the renders are
// thin. Claude Code's format also covers Cursor >= 2.4 (it reads
// `.claude/agents/` natively); Codex needs TOML. Tools with no definition
// format at all use the fallback documented in `.agents/profiles/README.md`.

import { join } from "@std/path";
import { GEN_MARKER } from "./markers.ts";
import { ChiselError, warn } from "./report.ts";
import { listFiles, pathExists, readTextIfPresent } from "./target.ts";

export interface ProfileText {
  /** A flat frontmatter value, or `""` when the file has no such key. */
  field(key: string): string;
  /** Everything after the frontmatter, leading blank lines trimmed. */
  readonly body: string;
}

/**
 * Splits a profile into its flat frontmatter and its body. A file that does
 * not open with a frontmatter fence has neither — which is how a
 * documentation page dropped in `profiles/` stays invisible to the renderer.
 */
export function parseProfile(text: string): ProfileText {
  const lines = text.split("\n");
  if (lines.at(-1) === "") lines.pop();
  const head = new Map<string, string>();
  let bodyStart = 0;
  if (lines[0] === "---") {
    let index = 1;
    while (index < lines.length && lines[index] !== "---") {
      const line = lines[index];
      const separator = line.indexOf(": ");
      if (separator > 0) {
        head.set(line.slice(0, separator), line.slice(separator + 2));
      }
      index += 1;
    }
    bodyStart = index + 1;
  }
  while (bodyStart < lines.length && lines[bodyStart] === "") bodyStart += 1;
  const bodyLines = lines.slice(bodyStart);
  return {
    field: (key: string) => head.get(key) ?? "",
    body: bodyLines.length === 0 ? "" : `${bodyLines.join("\n")}\n`,
  };
}

// Escape a one-line value for a double-quoted scalar. YAML's double-quoted
// style and TOML's basic string agree on the two characters that can occur
// here, so one helper serves both renders — and quoting is what keeps a
// description containing `: `, a leading `[`, or a `#` from breaking the
// frontmatter it lands in.
export function escapeDoubleQuoted(value: string): string {
  return value.replaceAll("\\", "\\\\").replaceAll('"', '\\"');
}

function provenance(sourceRelative: string): string {
  return `${GEN_MARKER} from ${sourceRelative} — do not edit: \`chisel update\` re-renders it.`;
}

export function renderClaudeDefinition(
  name: string,
  description: string,
  sourceRelative: string,
  body: string,
): string {
  return [
    "---",
    `name: "${escapeDoubleQuoted(name)}"`,
    `description: "${escapeDoubleQuoted(description)}"`,
    "---",
    "",
    `<!-- ${provenance(sourceRelative)} -->`,
    "",
    "",
  ].join("\n") + body;
}

export function renderCodexDefinition(
  name: string,
  description: string,
  sourceRelative: string,
  body: string,
): string {
  // TOML multi-line LITERAL strings do no escape processing at all, which is
  // what keeps a markdown body byte-identical through the render. The single
  // sequence they cannot carry is the delimiter itself.
  return [
    `# ${provenance(sourceRelative)}`,
    `name = "${escapeDoubleQuoted(name)}"`,
    `description = "${escapeDoubleQuoted(description)}"`,
    "developer_instructions = '''",
    "",
  ].join("\n") + body + "'''\n";
}

// Write rendered content over a definition chisel owns. A file that exists
// without the generated marker belongs to the user (their own sub-agent of
// the same name): warn and leave it alone rather than destroy it — the same
// stance chisel takes on a foreign `.claude/skills`.
async function installGenerated(
  destination: string,
  rendered: string,
): Promise<void> {
  const existing = await readTextIfPresent(destination);
  if (existing !== null && !existing.includes(GEN_MARKER)) {
    warn(
      `${destination} exists and was not generated by chisel — leaving it alone`,
    );
    return;
  }
  await Deno.writeTextFile(destination, rendered);
}

/** Renders every installed profile that names a role, into both formats. */
export async function renderAgentDefinitions(targetDir: string): Promise<void> {
  const profilesDir = join(targetDir, ".agents", "profiles");
  if (!(await pathExists(profilesDir))) return;

  const claudeDir = join(targetDir, ".claude", "agents");
  const codexDir = join(targetDir, ".codex", "agents");
  await Deno.mkdir(claudeDir, { recursive: true });
  await Deno.mkdir(codexDir, { recursive: true });

  for (const fileName of await listFiles(profilesDir)) {
    if (!fileName.endsWith(".md")) continue;
    const profilePath = join(profilesDir, fileName);
    const profile = parseProfile(await Deno.readTextFile(profilePath));
    const name = profile.field("name");
    if (name === "") continue;
    // The generated files are named after the role (`name` is the identity
    // every tool addresses it by), but the provenance pointer names the file
    // it actually came from — so it stays true even if the two ever differ.
    const sourceRelative = `.agents/profiles/${fileName}`;
    if (profile.body.includes("'''")) {
      throw new ChiselError(
        `profile ${profilePath} contains ''' — it cannot be rendered as TOML; rephrase it`,
      );
    }
    const description = profile.field("description");
    await installGenerated(
      join(claudeDir, `${name}.md`),
      renderClaudeDefinition(name, description, sourceRelative, profile.body),
    );
    await installGenerated(
      join(codexDir, `${name}.toml`),
      renderCodexDefinition(name, description, sourceRelative, profile.body),
    );
  }
}
