// The socle files that ship inside the package, relative to `socle/`.
//
// A published package is reached over HTTP, where a directory cannot be
// listed: the socle has to be named to be found. `test/integrity.test.ts`
// compares this list to a walk of `socle/`, so a file added upstream cannot
// silently stop shipping.
export const SOCLE_FILES: readonly string[] = [
  "agents/discipline.md",
  "agents/formulas/chisel-auto-light.formula.toml",
  "agents/formulas/chisel-auto.formula.toml",
  "agents/formulas/chisel-default.formula.toml",
  "agents/formulas/chisel-light.formula.toml",
  "agents/formulas/chisel-supervised.formula.toml",
  "agents/methodology.md",
  "agents/profiles/README.md",
  "agents/profiles/architect.md",
  "agents/profiles/checker.md",
  "agents/profiles/foreman.md",
  "agents/profiles/inspector.md",
  "agents/profiles/mason.md",
  "agents/project.md.tpl",
  "agents/reference.md",
  "agents/skills/chisel-beads/CHANGING-CASE.md",
  "agents/skills/chisel-beads/SKILL.md",
  "agents/skills/chisel-setup/SKILL.md",
  "agents/skills/code-review/SKILL.md",
  "agents/skills/codebase-design/DEEPENING.md",
  "agents/skills/codebase-design/DESIGN-IT-TWICE.md",
  "agents/skills/codebase-design/SKILL.md",
  "agents/skills/diagnosing-bugs/SKILL.md",
  "agents/skills/diagnosing-bugs/scripts/hitl-loop.template.sh",
  "agents/skills/domain-modeling/ADR-FORMAT.md",
  "agents/skills/domain-modeling/CONTEXT-FORMAT.md",
  "agents/skills/domain-modeling/SKILL.md",
  "agents/skills/grilling/SKILL.md",
  "agents/skills/handoff/SKILL.md",
  "agents/skills/improve-codebase-architecture/HTML-REPORT.md",
  "agents/skills/improve-codebase-architecture/SKILL.md",
  "agents/skills/prototype/LOGIC.md",
  "agents/skills/prototype/SKILL.md",
  "agents/skills/prototype/UI.md",
  "agents/skills/research/SKILL.md",
  "agents/skills/retro/SKILL.md",
  "agents/skills/slice-task/SKILL.md",
  "agents/skills/tdd/SKILL.md",
  "agents/skills/tdd/mocking.md",
  "agents/skills/tdd/tests.md",
  "agents/skills/upgrade-v2/SKILL.md",
  "agents/skills/wayfinder/SKILL.md",
  "agents/skills/writing-great-skills/GLOSSARY.md",
  "agents/skills/writing-great-skills/SKILL.md",
  "agents/user.md.tpl",
  "scripts/sync-upstream.sh",
  "scripts/sync-upstream/SKILL.md",
  "scripts/task-id.sh",
  "templates/000-template.spec.md",
  "templates/000-template.work.md",
  "templates/AGENTS-block.md",
];
